spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create  # 스키마 자동 생성
    show-sql: true      # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  logging:
    level:
      org:
        springframework:
          orm:
            jpa: DEBUG
jwt:
  key: ${JWT_SECRET_KEY}

  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: admin@gmail.com
#AWS S3
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: gennetimage # 버킷 이름 수정
    stack:
      auto-: false
    region:
      static: ap-northeast-2
